version: 0.2

phases:
  pre_build:
    commands:
      - echo Loging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=102888717683.dkr.ecr.eu-west-1.amazonaws.com/bugs
      - IMAGE_TAG=$(echo `date +%s`)
      - echo $IMAGE_TAG

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:bugs .
      - docker tag $REPOSITORY_URI:bugs $REPOSITORY_URI:bugs.$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:bugs
      - docker push $REPOSITORY_URI:bugs.$IMAGE_TAG
